### PR TITLE
define specification for board

### PR DESCRIPTION
**Pull request by generationmake**

### CODE REVIEW

**Comment by generationmake** [comment]
@aentinger , @wuehr1999 
any comments on this board?
Thanks

**Comment by generationmake** [comment]
+fuse
+quiic connector

**Comment by generationmake** [comment]
+ neopixel for status

+ maybe back EMF circuit for motor control???

**Comment by aentinger** [comment]
* Power-Pole connectors for battery power :wink:

I'd still drop the ultra-sound. It's effectively unusable in a professional setting. Imho it devalues any kind of platform, because if you put ultrasound on it it - in my opinion - shows that you've got no idea about sensors in the context of robotic applications.

**Comment by aentinger** [comment]
>maybe back EMF circuit for motor control???

Is that even relevant for DC motors? Probably yeah, but I wouldn't know how to implement it.

**Comment by generationmake** [comment]
add some output for LED or head lamp

**Pull request merged**
